
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[285] =
    {   0,
       92,   92,   95,   93,   92,   92,   73,   93,   64,   81,
       93,   82,   83,   80,   61,   89,   62,   90,   63,   43,
       43,   91,   88,   67,   48,   68,   79,   40,   84,   85,
       77,   93,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   86,   76,   87,
       78,   92,   66,    0,   47,    0,    0,   53,   71,   56,
        0,    0,   51,   59,   49,   60,   50,   45,    2,    1,
       52,   45,   42,    0,    0,    0,   43,   43,   43,   74,
       69,   65,   70,   75,   40,   57,    0,    0,    0,   40,
       40,   40,   40,   40,   40,   10,   40,   40,   40,   40,

       40,   40,   18,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   58,   72,   47,    0,    0,    0,
        0,   44,    0,    0,    0,   45,    1,   45,   42,   42,
        0,   46,   41,   43,   54,   55,    0,    0,    0,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       16,   40,   40,   19,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
        0,    0,    0,    0,   42,   46,   41,   41,   41,   43,
        0,    0,    0,    3,   40,    5,    6,   40,   40,   40,
       40,   12,   13,   40,   40,   17,   40,   20,   40,   40,

       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       32,   40,   40,    0,    0,    0,   42,   41,   41,   36,
        0,    0,    4,    7,   40,   40,   40,   40,   15,   40,
       40,   40,   40,   23,   40,   40,   40,   40,   40,   40,
       30,   40,   40,   34,   41,   41,   41,    0,    0,   40,
       40,   11,   14,   35,   40,   40,   22,   24,   25,   26,
       27,   28,   40,   40,   40,    0,    0,   40,    9,   40,
       40,   29,   40,   40,   37,    0,    8,   21,   39,   31,
       33,    0,   38,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   27,   30,   31,
       32,   32,   33,   32,   32,   34,   32,   32,   32,   32,
       32,   32,   32,   32,   35,   32,   32,   36,   32,   32,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   32,   51,   52,   53,   54,
       55,   56,   32,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    2,    3,    1,    1,    2,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    1,    6,    1,    1,
        7,    4,    4,    4,    4,    4,    4,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[292] =
    {   0,
        0,    0,  498,  499,   68,   71,  473,   74,  472,   69,
      457,  499,  499,  470,   65,  499,   64,   66,   70,   79,
       84,  499,  499,   67,  469,   81,  499,    0,  499,  499,
      468,   88,  431,  433,   71,   46,   70,   55,  434,   80,
      433,  441,   79,  422,  431,  429,  434,  499,   72,  499,
      499,  143,  499,  146,  147,  152,  188,  499,  499,  499,
      473,  246,  499,  499,  499,  499,  499,  146,  499,    0,
      499,  169,  260,  155,  204,    0,  267,  499,  126,  457,
      499,  499,  499,  456,    0,  499,  424,  423,  424,  417,
      429,  416,  431,  418,  424,  410,  411,  408,  408,  411,

      408,  405,    0,  104,  409,  109,  407,   75,  139,  411,
      404,   85,  120,  409,  499,  499,  206,  223,  231,  244,
        0,  499,  449,  186,    0,  499,    0,  298,  499,  168,
      238,  304,  306,  184,  499,  499,  402,  403,  413,  399,
      411,  406,  394,   73,  408,  406,  402,  394,  400,  403,
        0,  389,  393,    0,  394,  391,  381,  379,  381,  379,
      383,  361,  357,  357,  369,  359,  356,  360,  362,  350,
      324,  365,  328,  392,  207,  499,  255,  499,  214,  499,
      347,  342,  343,    0,  339,    0,    0,  329,  337,  326,
      330,    0,    0,  323,  319,    0,  323,    0,  318,  318,

      316,  313,  324,  314,  318,  321,  320,  318,  307,  311,
        0,  296,  308,  351,    0,  340,  499,  366,  247,  499,
      296,  289,    0,    0,  280,  279,  279,  267,    0,  269,
      255,  261,  256,    0,  263,  257,  254,  237,  242,  231,
        0,  217,  217,    0,    0,  499,  499,  214,  200,  184,
      184,    0,    0,    0,  193,  194,    0,    0,    0,    0,
        0,    0,  181,  181,  161,  148,  144,  137,    0,  125,
      120,    0,  124,  116,  499,  102,    0,    0,    0,    0,
        0,   73,  499,  499,  417,  420,  423,  430,  107,  104,
       77

    } ;

static const flex_int16_t yy_def[292] =
    {   0,
      284,    1,  284,  284,  284,  284,  284,  285,  284,  284,
      286,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  287,  284,  284,
      284,  284,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  284,  284,  284,
      284,  284,  284,  285,  284,  285,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  288,
      284,  284,  284,  284,  284,  289,  284,  284,  284,  284,
      284,  284,  284,  284,  287,  284,  284,  284,  284,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  284,  284,  284,  285,  285,  285,
      290,  284,  284,  284,  291,  284,  288,  284,  284,  284,
      284,  284,  289,  284,  284,  284,  284,  284,  284,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      285,  285,  284,  291,  284,  284,  133,  284,  284,  284,
      284,  284,  284,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  285,  172,  284,  284,  177,  284,  284,
      284,  284,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  133,  284,  284,  284,  284,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  284,  284,  287,  287,  287,
      287,  287,  287,  287,  284,  284,  287,  287,  287,  287,
      287,  284,  284,    0,  284,  284,  284,  284,  284,  284,
      284

    } ;

static const flex_int16_t yy_nxt[569] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   29,    4,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   28,   40,
       28,   41,   28,   28,   28,   28,   42,   43,   44,   45,
       46,   47,   28,   28,   28,   48,   49,   50,   51,   52,
       52,   52,   52,   52,   52,   54,   59,   64,   66,   55,
      174,   69,   54,   68,   68,   68,   70,   67,   65,   80,
       81,   95,   60,   71,   72,  115,   73,   73,   74,   72,

       96,   77,   77,   77,   83,   84,  100,  172,   75,  101,
      133,   57,   92,   75,   76,   87,   88,   78,   79,   93,
       89,   97,  160,   98,   75,   94,  103,  107,  108,   75,
      188,  189,   99,  104,  166,   78,  283,  109,  116,  161,
      110,   76,  167,   79,   52,   52,   52,   54,  117,  117,
      117,   55,  118,   54,   54,  153,  156,   55,  282,  134,
       54,  281,  154,   68,   68,   68,  157,  158,  280,  168,
       72,  169,   74,   74,   74,   75,  126,  134,  279,  126,
      162,  278,  277,   57,   75,  276,  128,  128,  128,   57,
       54,   75,  126,  119,  122,  163,  119,  126,   75,  126,

       75,  175,  126,  173,  173,  120,  120,  117,  117,  117,
      275,  118,  274,  119,   75,  126,  131,  180,  131,  175,
      126,  132,  132,  132,   54,  119,  273,  272,   55,  119,
      119,   54,   54,  119,  119,  180,   55,  271,  270,   54,
      217,  119,  269,  268,  119,   54,  119,  219,  119,   55,
      121,  123,   54,  267,  123,  132,  132,  132,  217,  266,
       57,  171,  171,  124,  124,  219,  265,  131,   57,  131,
      264,  123,  218,  218,  218,   72,  263,   73,   73,   74,
      247,   57,   72,  123,   77,   77,   77,  123,  123,   75,
      262,  123,  123,  129,  130,  261,   75,  260,  247,  123,

       78,   79,  123,  259,  123,   75,  123,  258,  125,  257,
      256,  129,   75,  255,  254,  128,  128,  128,   78,  130,
      253,  132,  132,  132,  252,   54,   79,   75,  126,   55,
      251,  126,   54,  250,  176,  177,  122,  176,  249,  178,
      179,  214,  214,   75,  126,  216,  216,  248,  122,  126,
      176,  177,   54,  244,  243,  176,   55,  178,  242,   54,
      241,   57,  240,  239,  238,  179,   54,  237,  236,  235,
       55,  234,  233,   54,  232,  231,  230,  229,  284,  228,
      284,  227,  215,  215,  215,  226,  225,  224,   57,  223,
      222,  215,  215,  215,  215,  215,  245,  221,  220,  246,

      122,  213,   57,  212,  211,  210,  215,  215,  215,  215,
      215,  215,  245,  209,  208,  207,  206,  246,   56,  205,
       56,   56,   56,   61,   61,   61,   85,   85,  204,   85,
      127,  127,  203,  127,  127,  127,  127,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      187,  186,  185,  184,  183,  182,  181,  122,  170,  165,
      164,  159,  155,  152,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  141,  140,  139,  138,  137,  136,
      135,  122,  114,  113,  112,  111,  106,  105,  102,   91,
       90,   86,   82,   63,   62,   58,   53,  284,    3,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284
    } ;

static const flex_int16_t yy_chk[569] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    6,    6,    6,    8,   10,   15,   17,    8,
      291,   19,    8,   18,   18,   18,   19,   17,   15,   24,
       24,   36,   10,   19,   20,   49,   20,   20,   20,   21,

       36,   21,   21,   21,   26,   26,   38,  290,   20,   38,
      289,    8,   35,   21,   20,   32,   32,   21,   21,   35,
       32,   37,  108,   37,   20,   35,   40,   43,   43,   21,
      144,  144,   37,   40,  112,   21,  282,   43,   49,  108,
       43,   20,  112,   21,   52,   52,   52,   54,   55,   55,
       55,   54,   55,   56,   54,  104,  106,   56,  276,   79,
       56,  274,  104,   68,   68,   68,  106,  106,  273,  113,
       74,  113,   74,   74,   74,   68,   68,   79,  271,   68,
      109,  270,  268,   54,   74,  267,   72,   72,   72,   56,
       57,   68,   68,   57,  124,  109,   57,   68,   72,   72,

       74,  130,   72,  124,  124,   57,   57,  117,  117,  117,
      266,  117,  265,   57,   72,   72,   75,  134,   75,  130,
       72,   75,   75,   75,  118,   57,  264,  263,  118,   57,
       57,  118,  119,   57,   57,  134,  119,  256,  255,  119,
      175,   57,  251,  250,   57,  120,   57,  179,   57,  120,
       57,   62,  120,  249,   62,  131,  131,  131,  175,  248,
      118,  120,  120,   62,   62,  179,  243,  177,  119,  177,
      242,   62,  177,  177,  177,   73,  240,   73,   73,   73,
      219,  120,   77,   62,   77,   77,   77,   62,   62,   73,
      239,   62,   62,   73,   73,  238,   77,  237,  219,   62,

       77,   77,   62,  236,   62,   73,   62,  235,   62,  233,
      232,   73,   77,  231,  230,  128,  128,  128,   77,   73,
      228,  132,  132,  132,  227,  171,   77,  128,  128,  171,
      226,  128,  171,  225,  132,  133,  173,  132,  222,  133,
      133,  171,  171,  128,  128,  173,  173,  221,  216,  128,
      132,  133,  214,  213,  212,  132,  214,  133,  210,  214,
      209,  171,  208,  207,  206,  133,  172,  205,  204,  203,
      172,  202,  201,  172,  200,  199,  197,  195,  218,  194,
      218,  191,  172,  172,  172,  190,  189,  188,  214,  185,
      183,  172,  172,  172,  172,  172,  218,  182,  181,  218,

      174,  170,  172,  169,  168,  167,  172,  172,  172,  172,
      172,  172,  218,  166,  165,  164,  163,  218,  285,  162,
      285,  285,  285,  286,  286,  286,  287,  287,  161,  287,
      288,  288,  160,  288,  288,  288,  288,  159,  158,  157,
      156,  155,  153,  152,  150,  149,  148,  147,  146,  145,
      143,  142,  141,  140,  139,  138,  137,  123,  114,  111,
      110,  107,  105,  102,  101,  100,   99,   98,   97,   96,
       95,   94,   93,   92,   91,   90,   89,   88,   87,   84,
       80,   61,   47,   46,   45,   44,   42,   41,   39,   34,
       33,   31,   25,   14,   11,    9,    7,    3,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "test.l"
#line 2 "test.l"
    #include <stdio.h>
    void onmatch(char * type);
    void handleComment();
    
    #define COMMENT "Comment"
    #define KEYWORD "Keyword"
    #define IDENTIFIER "Identifier"
    #define COMMENT "Comment"
    #define INT_CONST "Integer Constant"
    #define CHAR_CONST "Character Constant"
    #define REAL_CONST "Real Number Constant"
    #define STR_CONST "String Constant"
    #define ASSIGN_OP "Assignment Operator"
    #define INCRE_DECRE_OP "Increment or Decrement"
    #define ARITHMETIC_OP "Arithmetic Operator"
    #define COMPARISON_OP "Comparison Operator"
    #define LOGICAL_OP "Logical Operator"
    #define BIT_OP "Bit Operator"
    #define POINTER_OP "Pointer Operator"
    #define SIZEOF_OP "sizeof Operator"
    #define QUESTION_MARK "Question mark (?)"
    #define UNKNOWN "Unknown"
    #define LEFT_PARENTHESIS "Left Parenthesis"
    #define RIGHT_PARENTHESIS "Right Parenthesis"
    #define LEFT_BRACKET "Left Bracket"
    #define RIGHT_BRACKET "Right Bracket"
    #define LEFT_BRACE "Left Brace"
    #define RIGHT_BRACE "Right Brace"
    #define SEMICOLON "Semicolon"
    #define COMMA "Comma"
    #define DOT "Dot"
    #define COLON "Colon"
    #define STAR "*"
    #define AND "&"
#line 697 "lex.yy.c"
#line 698 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 52 "test.l"


#line 918 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 499 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 54 "test.l"
{onmatch(COMMENT);} 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 55 "test.l"
{ handleComment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 58 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 59 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 60 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 61 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 62 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 63 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 64 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 65 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 66 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 67 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 68 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 69 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 70 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 71 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 72 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 73 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 74 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 75 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 76 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 77 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 78 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 79 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 80 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 81 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 82 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 83 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 84 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 85 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 86 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 87 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 88 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 90 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 94 "test.l"
{ onmatch(KEYWORD); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 96 "test.l"
{ onmatch(IDENTIFIER); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 98 "test.l"
{ onmatch(INT_CONST); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 99 "test.l"
{ onmatch(INT_CONST); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 100 "test.l"
{ onmatch(INT_CONST); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 102 "test.l"
{onmatch(CHAR_CONST);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 104 "test.l"
{onmatch(REAL_CONST);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 105 "test.l"
{onmatch(REAL_CONST);}
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 107 "test.l"
{ onmatch(STR_CONST); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 109 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 110 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 111 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 112 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 113 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 114 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 115 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 116 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 117 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 118 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 119 "test.l"
{onmatch(ASSIGN_OP);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "test.l"
{onmatch(INCRE_DECRE_OP);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 122 "test.l"
{onmatch(INCRE_DECRE_OP);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 124 "test.l"
{onmatch(ARITHMETIC_OP);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 125 "test.l"
{onmatch(ARITHMETIC_OP);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 "test.l"
{onmatch(ARITHMETIC_OP);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 127 "test.l"
{onmatch(ARITHMETIC_OP);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 129 "test.l"
{onmatch(COMPARISON_OP);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 130 "test.l"
{onmatch(COMPARISON_OP);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 131 "test.l"
{onmatch(COMPARISON_OP);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 132 "test.l"
{onmatch(COMPARISON_OP);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 133 "test.l"
{onmatch(COMPARISON_OP);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 134 "test.l"
{onmatch(COMPARISON_OP);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 136 "test.l"
{onmatch(LOGICAL_OP);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 137 "test.l"
{onmatch(LOGICAL_OP);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 138 "test.l"
{onmatch(LOGICAL_OP);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 140 "test.l"
{onmatch(BIT_OP);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 141 "test.l"
{onmatch(BIT_OP);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 142 "test.l"
{onmatch(BIT_OP);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 143 "test.l"
{onmatch(BIT_OP);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 144 "test.l"
{onmatch(BIT_OP);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "test.l"
{onmatch(QUESTION_MARK);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 147 "test.l"
{onmatch(STAR);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 148 "test.l"
{onmatch(AND);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 151 "test.l"
{onmatch(LEFT_PARENTHESIS); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 152 "test.l"
{onmatch(RIGHT_PARENTHESIS);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 153 "test.l"
{onmatch(LEFT_BRACKET);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 154 "test.l"
{onmatch(RIGHT_BRACKET);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 155 "test.l"
{onmatch(LEFT_BRACE);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 156 "test.l"
{onmatch(RIGHT_BRACE);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 157 "test.l"
{onmatch(SEMICOLON);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 158 "test.l"
{onmatch(COMMA);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 159 "test.l"
{onmatch(DOT);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 160 "test.l"
{onmatch(COLON);}
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 162 "test.l"
{ /* ignored */}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 164 "test.l"
{ onmatch(UNKNOWN); return 1; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 167 "test.l"
ECHO;
	YY_BREAK
#line 1447 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 284);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 167 "test.l"


// char input() {
//     char buff[1];
//     int result;
//     YY_INPUT(buff, result, 1);
//     return buff[0];
// }

void handleComment() {
    printf("<"COMMENT", ");
    
    while(1) {
        char c = input();
        if (c == '*') {
            char c1 = input();
            if (c1 == '/') {
                break;
            } else {
                putchar(c);
            }
        } else {
            putchar(c);
        }
    }

    printf(">\n");

    
}

void onmatch(char * type) {
    printf("<%s, %s>\n", type, yytext);
}

int yywrap() 
{ 
   return(1); 
} 

int main()
{
    yylex();
}

