/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Apr 17 08:13:08 CST 2019
 */

package net.mooctest;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class NaiveBayesClassifier_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "net.mooctest.NaiveBayesClassifier"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(NaiveBayesClassifier_ESTest_scaffolding.class.getClassLoader() ,
      "com.github.javaparser.ast.stmt.ContinueStmt",
      "com.github.javaparser.ast.nodeTypes.NodeWithIdentifier",
      "com.github.javaparser.metamodel.ClassOrInterfaceDeclarationMetaModel",
      "com.github.javaparser.ast.stmt.WhileStmt",
      "com.github.javaparser.ast.nodeTypes.modifiers.NodeWithPrivateModifier",
      "com.github.javaparser.ast.stmt.UnparsableStmt",
      "com.github.javaparser.ast.nodeTypes.NodeWithBlockStmt",
      "com.github.javaparser.printer.SourcePrinter",
      "com.github.javaparser.ast.type.Type",
      "com.github.javaparser.ast.Node$ObserverRegistrationMode",
      "com.github.javaparser.ast.visitor.EqualsVisitor",
      "com.github.javaparser.ast.expr.Expression",
      "com.github.javaparser.ast.nodeTypes.modifiers.NodeWithAccessModifiers",
      "com.github.javaparser.ast.nodeTypes.NodeWithRange",
      "com.github.javaparser.ast.expr.SimpleName",
      "com.github.javaparser.ast.stmt.LabeledStmt",
      "com.github.javaparser.ast.body.TypeDeclaration",
      "com.github.javaparser.ast.type.VoidType",
      "net.mooctest.Classifier",
      "com.github.javaparser.ast.stmt.AssertStmt",
      "com.github.javaparser.ast.Modifier",
      "com.github.javaparser.ast.expr.VariableDeclarationExpr",
      "com.github.javaparser.ast.stmt.ThrowStmt",
      "com.github.javaparser.ast.visitor.Visitable",
      "com.github.javaparser.ast.stmt.SwitchEntryStmt",
      "com.github.javaparser.ast.visitor.GenericVisitor",
      "com.github.javaparser.ast.comments.Comment",
      "com.github.javaparser.ast.stmt.BlockStmt",
      "com.github.javaparser.HasParentNode",
      "com.github.javaparser.metamodel.LocalClassDeclarationStmtMetaModel",
      "com.github.javaparser.ast.expr.ArrayInitializerExpr",
      "com.github.javaparser.ast.nodeTypes.NodeWithOptionalBlockStmt",
      "com.github.javaparser.metamodel.BodyDeclarationMetaModel",
      "com.github.javaparser.ast.PackageDeclaration",
      "com.github.javaparser.ast.stmt.ExpressionStmt",
      "com.github.javaparser.metamodel.TypeDeclarationMetaModel",
      "com.github.javaparser.ast.expr.Name",
      "com.github.javaparser.ast.expr.AnnotationExpr",
      "com.github.javaparser.ast.AccessSpecifier",
      "com.github.javaparser.ast.Node$Parsedness",
      "com.github.javaparser.ast.nodeTypes.NodeWithTypeArguments",
      "com.github.javaparser.ast.nodeTypes.NodeWithAnnotations",
      "com.github.javaparser.ast.nodeTypes.modifiers.NodeWithStaticModifier",
      "com.github.javaparser.ast.comments.JavadocComment",
      "com.github.javaparser.ast.visitor.HashCodeVisitor",
      "com.github.javaparser.ast.expr.MarkerAnnotationExpr",
      "com.github.javaparser.ast.type.PrimitiveType$Primitive",
      "com.github.javaparser.ast.expr.SingleMemberAnnotationExpr",
      "com.github.javaparser.ast.stmt.SwitchStmt",
      "com.github.javaparser.ast.stmt.SynchronizedStmt",
      "net.mooctest.NaiveBayesClassifier",
      "com.github.javaparser.ast.comments.BlockComment",
      "com.github.javaparser.ast.nodeTypes.NodeWithConstructors",
      "com.github.javaparser.ast.Node$TreeTraversal",
      "com.github.javaparser.printer.PrettyPrinterConfiguration",
      "com.github.javaparser.metamodel.StatementMetaModel",
      "com.github.javaparser.ast.visitor.VoidVisitor",
      "com.github.javaparser.ast.expr.NameExpr",
      "com.github.javaparser.ast.stmt.IfStmt",
      "com.github.javaparser.ast.body.CallableDeclaration",
      "com.github.javaparser.ast.expr.NormalAnnotationExpr",
      "com.github.javaparser.ast.body.InitializerDeclaration",
      "com.github.javaparser.ast.body.MethodDeclaration",
      "com.github.javaparser.ast.nodeTypes.modifiers.NodeWithAbstractModifier",
      "com.github.javaparser.ast.nodeTypes.NodeWithCondition",
      "com.github.javaparser.utils.PositionUtils",
      "com.github.javaparser.ast.stmt.LocalClassDeclarationStmt",
      "com.github.javaparser.ast.nodeTypes.modifiers.NodeWithFinalModifier",
      "com.github.javaparser.ast.type.ClassOrInterfaceType",
      "com.github.javaparser.ast.nodeTypes.modifiers.NodeWithProtectedModifier",
      "com.github.javaparser.ast.observer.AstObserver",
      "com.github.javaparser.ast.nodeTypes.NodeWithExpression",
      "com.github.javaparser.ast.stmt.EmptyStmt",
      "com.github.javaparser.ast.stmt.ForeachStmt",
      "com.github.javaparser.ast.DataKey",
      "com.github.javaparser.ast.ImportDeclaration",
      "com.github.javaparser.ast.body.ConstructorDeclaration",
      "com.github.javaparser.ast.observer.Observable",
      "com.github.javaparser.ast.nodeTypes.NodeWithParameters",
      "com.github.javaparser.ast.nodeTypes.NodeWithSimpleName",
      "com.github.javaparser.ast.nodeTypes.NodeWithStatements",
      "com.github.javaparser.metamodel.NodeMetaModel",
      "com.github.javaparser.ast.CompilationUnit",
      "com.github.javaparser.ast.Node",
      "com.github.javaparser.ast.nodeTypes.NodeWithType",
      "com.github.javaparser.ast.NodeList",
      "com.github.javaparser.Range",
      "com.github.javaparser.ast.type.ReferenceType",
      "net.mooctest.IFeatureProbability",
      "com.github.javaparser.ast.nodeTypes.NodeWithDeclaration",
      "com.github.javaparser.ast.Node$1",
      "com.github.javaparser.ast.stmt.ExplicitConstructorInvocationStmt",
      "com.github.javaparser.ast.stmt.ForStmt",
      "com.github.javaparser.ast.nodeTypes.NodeWithJavadoc",
      "com.github.javaparser.metamodel.SimpleNameMetaModel",
      "com.github.javaparser.ast.nodeTypes.NodeWithVariables",
      "com.github.javaparser.ast.stmt.TryStmt",
      "com.github.javaparser.utils.Utils",
      "net.mooctest.Classification",
      "com.github.javaparser.resolution.Resolvable",
      "com.github.javaparser.ast.nodeTypes.modifiers.NodeWithStrictfpModifier",
      "com.github.javaparser.ast.body.ClassOrInterfaceDeclaration",
      "com.github.javaparser.TokenRange",
      "com.github.javaparser.printer.PrettyPrintVisitor",
      "com.github.javaparser.ast.observer.ObservableProperty$Type",
      "com.github.javaparser.ast.stmt.ReturnStmt",
      "com.github.javaparser.ast.body.Parameter",
      "com.github.javaparser.Position",
      "net.mooctest.NaiveBayesClassifier$1",
      "com.github.javaparser.metamodel.BaseNodeMetaModel",
      "com.github.javaparser.ast.stmt.DoStmt",
      "com.github.javaparser.ast.nodeTypes.NodeWithExtends",
      "com.github.javaparser.ast.body.VariableDeclarator",
      "com.github.javaparser.ast.nodeTypes.NodeWithBody",
      "com.github.javaparser.ast.nodeTypes.NodeWithName",
      "com.github.javaparser.ast.nodeTypes.NodeWithTokenRange",
      "com.github.javaparser.ast.nodeTypes.NodeWithTypeParameters",
      "com.github.javaparser.ast.nodeTypes.NodeWithOptionalLabel",
      "com.github.javaparser.printer.PrettyPrinter",
      "com.github.javaparser.ast.nodeTypes.NodeWithImplements",
      "com.github.javaparser.ast.nodeTypes.NodeWithModifiers",
      "com.github.javaparser.ast.type.ArrayType",
      "com.github.javaparser.ast.type.TypeParameter",
      "com.github.javaparser.ast.nodeTypes.NodeWithThrownExceptions",
      "com.github.javaparser.ast.body.BodyDeclaration",
      "com.github.javaparser.ast.stmt.Statement",
      "com.github.javaparser.ast.stmt.BreakStmt",
      "com.github.javaparser.ast.nodeTypes.NodeWithMembers",
      "com.github.javaparser.ast.observer.ObservableProperty",
      "com.github.javaparser.ast.comments.LineComment",
      "com.github.javaparser.ast.body.FieldDeclaration",
      "com.github.javaparser.ast.type.PrimitiveType",
      "com.github.javaparser.ast.nodeTypes.modifiers.NodeWithPublicModifier"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.lang.annotation.Annotation", false, NaiveBayesClassifier_ESTest_scaffolding.class.getClassLoader()));
  }
}
