%{

%}
%token IDENTIFIER
%token INT_CONST FLOAT_CONST CHAR_CONST STR_CONST
%token AUTO BREAK CASE CHAR CONST CONTINUE DEFAULT DO DOUBLE ELSE ENUM EXTERN FLOAT FOR GOTO IF INT LONG REGISTER RETURN SHORT SIGNED SIZEOF STATIC STRUCT SWITCH TYPEDEF UNION UNSIGNED VOID VOLATILE WHILE INLINE _BOOL _COMPLEX _IMAGINARY RESTRICT
%%