// keywords
#define AUTO "AUTO"
#define BREAK "BREAK"
#define CASE "CASE"
#define CHAR "CHAR"
#define CONST "CONST"
#define CONTINUE "CONTINUE"
#define DEFAULT "DEFAULT"
#define DO "DO"
#define DOUBLE "DOUBLE"
#define ELSE "ELSE"
#define ENUM "ENUM"
#define EXTERN "EXTERN"
#define FLOAT "FLOAT"
#define FOR "FOR"
#define GOTO "GOTO"
#define IF "IF"
#define INT "INT"
#define LONG "LONG"
#define REGISTER "REGISTER"
#define RETURN "RETURN"
#define SHORT "SHORT"
#define SIGNED "SIGNED"
#define SIZEOF "SIZEOF"
#define STATIC "STATIC"
#define STRUCT "STRUCT"
#define SWITCH "SWITCH"
#define TYPEDEF "TYPEDEF"
#define UNION "UNION"
#define UNSIGNED "UNSIGNED"
#define VOID "VOID"
#define VOLATILE "VOLATILE"
#define WHILE "WHILE"
#define INLINE "INLINE"
#define _BOOL "_BOOL"
#define _COMPLEX "_COMPLEX"
#define _IMAGINARY "_IMAGINARY"
#define RESTRICT "RESTRICT"

#define COMMENT "Comment"

#define IDENTIFIER "Identifier"

#define INT_CONST "Integer Constant"
#define CHAR_CONST "Character Constant"
#define REAL_CONST "Real Number Constant"
#define STR_CONST "String Constant"

#define ASSIGN_OP "Assignment Operator"

#define INCRE_DECRE_OP "Increment or Decrement"
#define ARITHMETIC_OP "Arithmetic Operator"
#define COMPARISON_OP "Comparison Operator"
#define LOGICAL_OP "Logical Operator"
#define BIT_OP "Bit Operator"
#define POINTER_OP "Pointer Operator"
#define SIZEOF_OP "sizeof Operator"
#define QUESTION_MARK "Question mark"
#define UNKNOWN "Unknown"
#define LEFT_PARENTHESIS "Left Parenthesis"
#define RIGHT_PARENTHESIS "Right Parenthesis"
#define LEFT_BRACKET "Left Bracket"
#define RIGHT_BRACKET "Right Bracket"
#define LEFT_BRACE "Left Brace"
#define RIGHT_BRACE "Right Brace"
#define SEMICOLON "Semicolon"
#define COMMA "Comma"
#define DOT "Dot"
#define COLON "Colon"
#define ELLIPSIS "Ellipsis"

#define STAR "STAR"
#define AND "AND"
#define PLUS "PLUS"
#define MINUS "MINUS"